name: Sync output with s3

on:
  pull_request:
    paths:
      - '.github/workflows/aws-sync.yml'
  workflow_dispatch:
  schedule:
    - cron: 30 20 * * *

jobs:
  deploy:
    strategy:
      matrix:
        repo: [ 'tarantool/tarantool', 'tarantool/tarantool-ee' ]
        dir: [ 'artifacts', 'workflow_runs', 'workflow_run_jobs' ]
    runs-on: ['self-hosted', 'multivac-crawler']
    steps:
      - uses: actions/checkout@v3
      - name: Sync fetched data
        run: ./backup.sh ${{ matrix.repo }}/${{ matrix.dir }}

      - name: Set the chat for failure notification
        if: failure()
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo "CHAT_ID=${{ secrets.MYTEAM_SERVICE_CHAT_ID }}" >> "$GITHUB_ENV"
          else
              echo "CHAT_ID=${{ secrets.MYTEAM_DEBUG_CHAT_ID }}" >> "$GITHUB_ENV"
          fi

      - name: Send notification
        if: failure()
        uses: dasshit/myteam-notify@master
        with:
          api-url: ${{ secrets.MYTEAM_BOT_API }}
          bot-token: ${{ secrets.VKTEAMS_TARANTOOLBOT_TOKEN }}
          chat-id: ${{ env.CHAT_ID }}
          msg-text: "multivac s3 sync failure:
                    https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
