name: Sync output with s3

on:
  pull_request:
    paths:
      - '.github/workflows/aws-sync.yml'
  workflow_dispatch:
  schedule:
    - cron: 30 20 * * *

jobs:
  deploy:
    runs-on: ['self-hosted', 'multivac-crawler']
    steps:
      - uses: actions/checkout@v3
      - name: Sync workflow_runs
        run: ./backup.sh workflow_runs

      - name: Sync workflow_run_jobs
        run: ./backup.sh workflow_run_jobs

      - name: Set the chat for failure notification
        if: failure()
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo "CHAT_ID=${{ secrets.MYTEAM_SERVICE_CHAT_ID }}" >> "$GITHUB_ENV"
          else
              echo "CHAT_ID=${{ secrets.MYTEAM_DEBUG_CHAT_ID }}" >> "$GITHUB_ENV"
          fi

      - name: Send notification
        if: failure()
        uses: dasshit/myteam-notify@master
        with:
          api-url: ${{ secrets.MYTEAM_BOT_API }}
          bot-token: ${{ secrets.MYTEAM_BOT_TOKEN }}
          chat-id: ${{ env.CHAT_ID }}
          msg-text: "multivac s3 sync failure:
                    https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
